strict: true
site_name: tuxpkg
site_author: TuxSuite Team
site_dir: public
site_description: |
  tuxpkg, by Linaro, is a command line tool. tuxpkg - release automation tool for Python projects
repo_url: https://gitlab.com/Linaro/tuxpkg/

theme:
  name: material
  logo: tuxpkg.svg
  favicon: tuxpkg.svg


markdown_extensions:
- admonition
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- toc:
    permalink: true

nav:
- Getting Started: index.md
- Installing tuxpkg:
  - PyPI: install-pypi.md
  - Debian packages: install-deb.md
  - RPM packages: install-rpm.md
  - Run uninstalled: run-uninstalled.md
- Running:
  - Subcommands: subcommands.md
